### ISSUE TITLE
Server crashes on startup

### ISSUE THREAD

**Issue by y2k04** [arthurbambou/Fabric---Discord-Link#127]
**Describe the bug**
Server is not starting up and is instead crashing.

**Reproduction steps**
I followed the steps, copied the bot token to the token string section of the config JSON file.

**Expected behaviour**
Worked lmaoo

<details> 
  <summary><strong>Crash report</strong></summary>
 

```

[11:36:44] [ForkJoinPool-1-worker-3/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
--
2 | - Unsupported root entry "$schema" at line 2 column 14
3 | [11:36:44] [ForkJoinPool-1-worker-3/WARN]: The mod "autoconfig1u" contains invalid entries in its mod json:
4 | - Unsupported root entry "$schema" at line 2 column 14
5 | [11:36:45] [main/INFO]: [FabricLoader] Loading 92 mods: fabric-renderer-api-v1@0.4.1+ca58154a7d, fabric-keybindings-v0@0.2.1+ca58154a7d, fabricloader@0.11.1, org_apache_commons_commons-collections4@4.1, com_fasterxml_jackson_core_jackson-annotations@2.10.1, better_wandering_trader@1.6.2, org_jetbrains_kotlinx_kotlinx-coroutines-core@1.3.7, fabric-structure-api-v1@1.1.4+ca58154a7d, crawl@0.8.1, fabric-containers-v0@0.1.10+ca58154a7d, falling_tree@2.10.0, fabric-object-builder-api-v1@1.9.3+ca58154a7d, fabric-dimensions-v1@2.0.2+ca58154a7d, java@11, fdlink_1_15_2@0.8.4, com_squareup_okio_okio@1.17.2, fabric-game-rule-api-v1@1.0.6+ca58154a7d, fabric-api-base@0.2.0+daa38b3d7d, fabric-rendering-data-attachment-v1@0.1.5+ca58154a7d, mm@2.1, fabric-textures-v0@1.0.6+ca58154a7d, fabric-rendering-fluids-v1@0.1.13+ca58154a7d, com_fasterxml_jackson_core_jackson-databind@2.10.1, trees-do-not-float@2.1.128, iamverysmart@2.1.0+mc1.16.1, org_jetbrains_kotlin_kotlin-stdlib@1.3.72, com_neovisionaries_nv-websocket-client@2.10, fabric-blockrenderlayer-v1@1.1.5+ca58154a7d, glassdoor@1.5.0-1.16, fabric-lifecycle-events-v1@1.2.1+ca58154a7d, net_sf_trove4j_trove4j@3.0.3, fabric-renderer-registries-v1@2.2.1+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk7@1.3.72, fabric-loot-tables-v1@1.0.2+ca58154a7d, com_vdurmont_emoji-java@5.1.1, club_minnced_discord-webhooks@0.5.4, com_fasterxml_jackson_core_jackson-core@2.10.1, fabric@0.29.4+1.16, org_slf4j_slf4j-api@1.7.25, fabric-particles-v1@0.2.4+ca58154a7d, fabric-diagonal-panes@0.4.0, fabric-networking-v0@0.3.2+ca58154a7d, fdlink_common@0.8.4, fdlink_1_8_9@0.8.4, fabric-screen-handler-api-v1@1.1.1+ca58154a7d, fabric-networking-blockentity-v0@0.2.8+ca58154a7d, fdlink_1_7_10@0.8.4, minecraft@1.16.5, fabric-command-api-v1@1.0.10+ca58154a7d, cloth-basic-math@0.5.1, jankson@3.0.1+j1.2.0, fabric-tool-attribute-api-v1@1.2.6+ca58154a7d, org_jetbrains_kotlin_kotlin-stdlib-jdk8@1.3.72, fabric-renderer-indigo@0.4.4+ca58154a7d, fdlink_1_12_2@0.8.4, fabric-item-api-v1@1.2.1+ca58154a7d, fabric-events-interaction-v0@0.4.2+ca58154a7d, fabric-crash-report-info-v1@0.1.3+ca58154a7d, net_dv8tion_jda@4.2.0_224, fabric-language-kotlin@1.3.72+build.1, fabric-entity-events-v1@1.0.3+ca58154a7d, fabric-rendering-v0@1.1.2+ca58154a7d, fabric-rendering-v1@1.5.1+ca58154a7d, fabric-key-binding-api-v1@1.0.2+ca58154a7d, cloth-config2@4.8.3, sit@1.16.2-9, org_jetbrains_kotlinx_kotlinx-coroutines-jdk8@1.3.7, fabric-resource-loader-v0@0.4.2+ca58154a7d, org_slf4j_slf4j-nop@1.7.25, autoconfig1u@3.3.1, malilib@0.10.0-dev.21+arne.2, org_jetbrains_kotlin_kotlin-reflect@1.3.72, fabric-content-registries-v0@0.2.1+ca58154a7d, org_json_json@20170516, fabric-tag-extensions-v0@1.1.1+ca58154a7d, fabric-biome-api-v1@3.1.1+ca58154a7d, architectury@1.5.101, fabric-registry-sync-v0@0.7.4+ca58154a7d, fabric-commands-v0@0.2.2+ca58154a7d, com_squareup_okhttp3_okhttp@3.13.0, fabric-mining-levels-v0@0.1.3+ca58154a7d, fabric-networking-api-v1@1.0.1+ca58154a7d, fabric-events-lifecycle-v0@0.2.1+ca58154a7d, fabric-models-v0@0.2.1+ca58154a7d, fabric-item-groups-v0@0.2.3+ca58154a7d, betterend@0.8.8-beta, shulkerboxtooltip@2.3.4+1.16.4, fabric-object-builders-v0@0.7.2+ca58154a7d, fdlink@0.8.4, fdlink_1_16@0.8.4, org_jetbrains_annotations@17.0.0, fabric-mumblelink-mod@0.7.5
6 | [11:36:45] [main/WARN]: Mod `net_dv8tion_jda` (4.2.0_224) does not respect SemVer - comparison support is limited.
7 | [11:36:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/server/fabric.jar Service=Knot/Fabric Env=SERVER
8 | [11:36:52] [main/WARN]: Error loading class: net/minecraft/class_746 (java.lang.ClassNotFoundException: net/minecraft/class_746)
9 | [11:36:52] [main/WARN]: @Mixin target net.minecraft.class_746 was not found architectury.mixins.json:PlayerAttackInvoker
10 | [11:36:52] [main/WARN]: Error loading class: net/minecraft/class_745 (java.lang.ClassNotFoundException: net/minecraft/class_745)
11 | [11:36:52] [main/WARN]: @Mixin target net.minecraft.class_745 was not found architectury.mixins.json:PlayerAttackInvoker
12 | [11:37:41] [main/INFO]: Definitely not up to no good
13 | [11:37:57] [main/INFO]: Looking for config file(s).
14 | [11:37:57] [main/INFO]: Reading config file(s).
15 | [11:37:57] [main/INFO]: Initializing 1.16 Compat module
16 | [11:37:57] [main/FATAL]: Failed to start the minecraft server
17 | java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'fdlink_common'!
18 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric.jar:?]
19 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric.jar:?]
20 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric.jar:?]
21 | at net.minecraft.server.Main.main(Main.java:92) [intermediary-server.jar:?]
22 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
23 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
24 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
25 | at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
26 | at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric.jar:?]
27 | at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:139) [fabric.jar:?]
28 | at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:27) [fabric.jar:?]
29 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
30 | at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
31 | at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
32 | at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
33 | at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric.jar:?]
34 | at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric.jar:?]
35 | at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric.jar:?]
36 | Caused by: java.lang.NullPointerException
37 | at fr.arthurbambou.fdlink.config.manager.ConfigHandler.readList(ConfigHandler.java:202) ~[f4ef2ce4-bae4-479f-b600-6a6758ba2274.jar:?]
38 | at fr.arthurbambou.fdlink.config.manager.ConfigHandler.parseConfig(ConfigHandler.java:169) ~[f4ef2ce4-bae4-479f-b600-6a6758ba2274.jar:?]
39 | at fr.arthurbambou.fdlink.config.manager.ConfigHandler.getConfig(ConfigHandler.java:90) ~[f4ef2ce4-bae4-479f-b600-6a6758ba2274.jar:?]
40 | at fr.arthurbambou.fdlink.FDLink.initialize(FDLink.java:24) ~[f4ef2ce4-bae4-479f-b600-6a6758ba2274.jar:?]
41 | at fr.arthurbambou.fdlink.FDLink.onInitializeServer(FDLink.java:20) ~[f4ef2ce4-bae4-479f-b600-6a6758ba2274.jar:?]
42 | at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric.jar:?]
43 | ... 17 more
```

</details>

**Additional context**
- Minecraft version: Fabric 1.16.5
- Fabric-Discord Link version: 0.8.4
- :exclamation: A list of all mods you were using:
architectury-1.5.101-fabric.jar
better-end-0.8.8-beta.jar
better-wandering-trader-1.6.2.jar
crawl-0.8.1.jar
fabric-diagonal-panes-0.4.0.jar
Fabric-Discord-Link-0.8.4.jar
FallingTree-Fabric-1.16.5-2.10.0.jar
glassdoor-1.5.0-1.16.jar
i-am-very-smart-2.1.0+mc1.16.1.jar
malilib-fabric-1.16.4-0.10.0-dev.21+arne.2.jar
shulkerboxtooltip-2.3.4+1.16.4.jar
sit-1.16.2-9.jar
tdnf-mc116-2.1.128.jar

**fdlink.json**
```{
  "chatChannels": [
      "<channel id removed for privacy>"
      ],
  "logChannels": [],
  "webhookURL": "",
  "ignoreBots": true,
  "activityUpdateInterval": 120,
  "minecraftToDiscord": {
    "general": {
      "enableDebugLogs": false
    },
    "chatChannels": {
      "commandPrefix": "-",
      "allowDiscordCommands": false,
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": true,
      "playerMessages": true,
      "teamPlayerMessages": true,
      "joinAndLeaveMessages": true,
      "advancementMessages": true,
      "challengeMessages": true,
      "goalMessages": true,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": true
    },
    "logChannels": {
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": true,
      "playerMessages": false,
      "teamPlayerMessages": false,
      "joinAndLeaveMessages": true,
      "advancementMessages": false,
      "challengeMessages": false,
      "goalMessages": false,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": true,
      "atATellRaw": false,
      "achievementMessages": true
    }
  },
  "discordToMinecraft": {
    "pingLongVersion": false
  },
  "version": 8,
  "token": "<token removed for bot privacy>"
}```

**Comment by thecatcore** [comment]
Can you send your message config too?

**Comment by thecatcore** [comment]
It crashed because your removed the "emojiMap" field

**Comment by thecatcore** [comment]
To fix it, simply add `"emojiMap":[]` to your config file

**Comment by y2k04** [comment]
Thanks
