### ISSUE TITLE
"Watching Server" Crash on Startup

### ISSUE THREAD

**Issue by Avakining** [arthurbambou/Fabric---Discord-Link#129]
**Describe the bug**
Each time I start dedicated server, it crashes a few seconds after loading the world.

**Reproduction steps**
1. Add mod to minecraft server
2. Set up bot exactly as told
3. launch minecraft server once, to generate config file (it does not crash)
4. add token and channel ids to config file
5. add bot to discord server using the link provided [here](https://github.com/arthurbambou/Fabric---Discord-Link/wiki/How-to-get-a-token-and-channel-ID-for-Discord)
6. launch server again, it crashes

**Expected behaviour**
Server launches, chat is linked to discord, everyone is happy, people can play :D

<details> 
  <summary><strong>Crash report</strong></summary>
 

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2/8/21 4:02 PM
Description: Watching Server

java.lang.Error: Watchdog
	at net.minecraft.class_3178.run(class_3178.java:52)
	at java.lang.Thread.run(Thread.java:748)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Thread Dump --
Details:
	Threads: "AWT-EventQueue-0" Id=181 RUNNABLE
	at javax.swing.text.AbstractDocument$AbstractElement.<init>(AbstractDocument.java:1774)
	at javax.swing.text.AbstractDocument$LeafElement.<init>(AbstractDocument.java:2502)
	at javax.swing.text.AbstractDocument.createLeafElement(AbstractDocument.java:1275)
	at javax.swing.text.PlainDocument.insertUpdate(PlainDocument.java:200)
	at javax.swing.text.AbstractDocument.handleInsertString(AbstractDocument.java:745)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:707)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at net.minecraft.class_3182.method_13970(class_3182.java:175)
	...


"AWT-Shutdown" Id=182 WAITING on java.lang.Object@36e0c5c7
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.Object@36e0c5c7
	at java.lang.Object.wait(Object.java:502)
	at sun.awt.AWTAutoShutdown.run(AWTAutoShutdown.java:295)
	at java.lang.Thread.run(Thread.java:748)


"JDA RateLimit-Worker 5" Id=180 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"JDA RateLimit-Worker 4" Id=176 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"IO-Worker-20" Id=175 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"IO-Worker-19" Id=174 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"Server Watchdog" Id=173 RUNNABLE
	at sun.management.ThreadImpl.dumpThreads0(Native Method)
	at sun.management.ThreadImpl.dumpAllThreads(ThreadImpl.java:454)
	at net.minecraft.class_3178.run(class_3178.java:49)
	at java.lang.Thread.run(Thread.java:748)


"IO-Worker-18" Id=172 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"IO-Worker-17" Id=171 TIMED_WAITING on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.SynchronousQueue$TransferStack@3c18aeb7
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.SynchronousQueue$TransferStack.awaitFulfill(SynchronousQueue.java:460)
	at java.util.concurrent.SynchronousQueue$TransferStack.transfer(SynchronousQueue.java:362)
	at java.util.concurrent.SynchronousQueue.poll(SynchronousQueue.java:941)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1073)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"Netty Server IO #0" Id=168 RUNNABLE
	at sun.nio.ch.KQueueArrayWrapper.kevent0(Native Method)
	at sun.nio.ch.KQueueArrayWrapper.poll(KQueueArrayWrapper.java:198)
	at sun.nio.ch.KQueueSelectorImpl.doSelect(KQueueSelectorImpl.java:117)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	-  locked io.netty.channel.nio.SelectedSelectionKeySet@791a2750
	-  locked java.util.Collections$UnmodifiableSet@49641b49
	-  locked sun.nio.ch.KQueueSelectorImpl@48293b7b
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at io.netty.channel.nio.SelectedSelectionKeySetSelector.select(SelectedSelectionKeySetSelector.java:62)
	at io.netty.channel.nio.NioEventLoop.select(NioEventLoop.java:756)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:411)
	...


"ObjectCleanerThread" Id=167 TIMED_WAITING on java.lang.ref.ReferenceQueue$Lock@31bd59df
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@31bd59df
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at io.netty.util.internal.ObjectCleaner$1.run(ObjectCleaner.java:54)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)


"Server console handler" Id=166 RUNNABLE (in native)
	at java.io.FileInputStream.readBytes(Native Method)
	at java.io.FileInputStream.read(FileInputStream.java:255)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:284)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	-  locked java.io.BufferedInputStream@1935d81f
	at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	-  locked java.io.InputStreamReader@70622623
	at java.io.InputStreamReader.read(InputStreamReader.java:184)
	...


"DestroyJavaVM" Id=165 RUNNABLE


"Thread-108" Id=162 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@711139b7
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@711139b7
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.mojang.util.QueueLogAppender.getNextLogEvent(QueueLogAppender.java:77)
	at net.minecraft.class_3182.method_13972(class_3182.java:137)
	at net.minecraft.class_3182$$Lambda$4451/827909315.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748)


"TimerQueue" Id=163 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1d7b2583
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@1d7b2583
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.DelayQueue.take(DelayQueue.java:211)
	at javax.swing.TimerQueue.run(TimerQueue.java:174)
	at java.lang.Thread.run(Thread.java:748)

	Number of locked synchronizers = 1
	- java.util.concurrent.locks.ReentrantLock$NonfairSync@2ab9f5eb


"Java2D Disposer" Id=160 WAITING on java.lang.ref.ReferenceQueue$Lock@7c494b31
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@7c494b31
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at sun.java2d.Disposer.run(Disposer.java:148)
	at java.lang.Thread.run(Thread.java:748)


"Java2D Queue Flusher" Id=159 TIMED_WAITING on sun.java2d.opengl.OGLRenderQueue$QueueFlusher@4ed198e
	at java.lang.Object.wait(Native Method)
	-  waiting on sun.java2d.opengl.OGLRenderQueue$QueueFlusher@4ed198e
	at sun.java2d.opengl.OGLRenderQueue$QueueFlusher.run(OGLRenderQueue.java:203)


"AppKit Thread" Id=157 RUNNABLE (in native)


"Snooper Timer" Id=156 WAITING on java.util.TaskQueue@611ea255
	at java.lang.Object.wait(Native Method)
	-  waiting on java.util.TaskQueue@611ea255
	at java.lang.Object.wait(Object.java:502)
	at java.util.TimerThread.mainLoop(Timer.java:526)
	at java.util.TimerThread.run(Timer.java:505)


"Worker-Main-13" Id=153 TIMED_WAITING on java.util.concurrent.ForkJoinPool@258dd4c8
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.ForkJoinPool@258dd4c8
	at java.util.concurrent.ForkJoinPool.awaitWork(ForkJoinPool.java:1835)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1704)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172)


"JDA MainWS-WriteThread" Id=146 WAITING on com.neovisionaries.ws.client.WritingThread@13ab038b
	at java.lang.Object.wait(Native Method)
	-  waiting on com.neovisionaries.ws.client.WritingThread@13ab038b
	at java.lang.Object.wait(Object.java:502)
	at com.neovisionaries.ws.client.WritingThread.waitForFrames(WritingThread.java:305)
	at com.neovisionaries.ws.client.WritingThread.main(WritingThread.java:89)
	at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:55)
	at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45)


"JDA MainWS-ReadThread" Id=145 RUNNABLE (in native)
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:475)
	at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:469)
	at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:69)
	at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1228)
	...


"JDA Gateway-Worker 1" Id=139 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@209ef299
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@209ef299
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"JDA RateLimit-Worker 3" Id=137 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"JDA RateLimit-Worker 2" Id=130 TIMED_WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at java.util.concurrent.locks.LockSupport.parkNanos(LockSupport.java:215)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2078)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1093)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"JDA RateLimit-Worker 1" Id=129 WAITING on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at sun.misc.Unsafe.park(Native Method)
	-  waiting on java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject@38272d6b
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2039)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:1088)
	at java.util.concurrent.ScheduledThreadPoolExecutor$DelayedWorkQueue.take(ScheduledThreadPoolExecutor.java:809)
	at java.util.concurrent.ThreadPoolExecutor.getTask(ThreadPoolExecutor.java:1074)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1134)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	...


"Timer hack thread" Id=127 TIMED_WAITING
	at java.lang.Thread.sleep(Native Method)
	at net.minecraft.class_156$6.run(class_156.java:636)


"Signal Dispatcher" Id=4 RUNNABLE


"Finalizer" Id=3 WAITING on java.lang.ref.ReferenceQueue$Lock@6b621a5a
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.ReferenceQueue$Lock@6b621a5a
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:144)
	at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:165)
	at java.lang.ref.Finalizer$FinalizerThread.run(Finalizer.java:216)


"Reference Handler" Id=2 WAITING on java.lang.ref.Reference$Lock@268138ae
	at java.lang.Object.wait(Native Method)
	-  waiting on java.lang.ref.Reference$Lock@268138ae
	at java.lang.Object.wait(Object.java:502)
	at java.lang.ref.Reference.tryHandlePending(Reference.java:191)
	at java.lang.ref.Reference$ReferenceHandler.run(Reference.java:153)




-- Performance stats --
Details:
	Random tick rate: 3
	Level stats: ResourceKey[minecraft:dimension / minecraft:overworld]: players: 0, entities: 729 [minecraft:chicken:124,minecraft:sheep:87,minecraft:item_frame:80,minecraft:villager:62,minecraft:item:53], block_entities: 1092 [minecraft:chest:397,minecraft:skull:358,minecraft:hopper:168,minecraft:furnace:50,minecraft:mob_spawner:21], block_ticks: 4393, fluid_ticks: 2534, chunk_source: ServerChunkCache: 6126,
ResourceKey[minecraft:dimension / minecraft:the_nether]: players: 0, entities: 4 [minecraft:strider:2,minecraft:item_frame:2], block_entities: 1 [minecraft:mob_spawner:1], block_ticks: 0, fluid_ticks: 142, chunk_source: ServerChunkCache: 1458,
ResourceKey[minecraft:dimension / minecraft:the_end]: players: 0, entities: 2 [minecraft:item_frame:2], block_entities: 0 [], block_ticks: 0, fluid_ticks: 0, chunk_source: ServerChunkCache: 1458
Stacktrace:
	at net.minecraft.class_3178.run(class_3178.java:52)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Mac OS X (x86_64) version 10.16
	Java Version: 1.8.0_281, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 7251235824 bytes (6915 MB) / 10587996160 bytes (10097 MB) up to 10587996160 bytes (10097 MB)
	CPUs: 8
	JVM Flags: 2 total; -Xmx10240M -Xms10240M
	Fabric Mods: 
		anvil_fix: AnvilFix 1.2.1-1.16
		autoconfig1u: Auto Config v1 Updated 3.3.1
		bettercaves: YUNG's Better Caves 1.16.2-1.0.3
		bettermineshafts: YUNG's Better Mineshafts 1.16.4-1.0
		chunky-fabric: Chunky 1.2.8
		cloth-basic-math: Cloth Basic Math 0.5.1
		cloth-client-events-v0: Cloth Client Events v0 1.4.5
		cloth-config2: Cloth Config v4 4.8.3
		club_minnced_discord-webhooks: discord-webhooks 0.5.4
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.10
		com_squareup_okhttp3_okhttp: okhttp 3.13.0
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		couplings: Couplings 1.3.3
		fabric: Fabric API 0.30.0+1.16
		fabric-api-base: Fabric API Base 0.2.0+ab87788d3a
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.1+ca58154a7d
		fabric-command-api-v1: Fabric Command API (v1) 1.0.10+ca58154a7d
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+ca58154a7d
		fabric-containers-v0: Fabric Containers (v0) 0.1.10+ca58154a7d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.1+ca58154a7d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.3+ca58154a7d
		fabric-dimensions-v1: fabric-dimensions-v1 2.0.2+ca58154a7d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.0.3+ca58154a7d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.2+ca58154a7d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+ca58154a7d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.6+ca58154a7d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.1+ca58154a7d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.3+ca58154a7d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.1+ca58154a7d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.2+ca58154a7d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+ca58154a7d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.1+ca58154a7d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.8+ca58154a7d
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+ca58154a7d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.3+ca58154a7d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.2+ca58154a7d
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+ca58154a7d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.4+ca58154a7d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+ca58154a7d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.2+ca58154a7d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.1+ca58154a7d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.4+ca58154a7d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.1+ca58154a7d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.6+ca58154a7d
		fabric-tpa: FabricTPA 1.4.1
		fabricloader: Fabric Loader 0.11.0
		fastfurnace: FastFurnace 2.3
		fdlink: Fabric <-> Discord Link 0.8.8
		fdlink_1_12_2: Fabric <-> Discord Link 0.8.8
		fdlink_1_15_2: Fabric <-> Discord Link 0.8.8
		fdlink_1_16: Fabric <-> Discord Link 0.8.8
		fdlink_1_5_2: Fabric <-> Discord Link 0.8.8
		fdlink_1_6_4: Fabric <-> Discord Link 0.8.8
		fdlink_1_7_10: Fabric <-> Discord Link 0.8.8
		fdlink_1_8_9: Fabric <-> Discord Link 0.8.8
		fdlink_common: Fabric <-> Discord Link 0.8.8
		fiber: fiber 0.23.0-2
		java: Java HotSpot(TM) 64-Bit Server VM 8
		lengthyladders: Lengthy Ladders 1.0.1
		lithium: Lithium 0.6.3
		mesh: Mesh 0.6.1-alpha.21+1.16.4
		mesh_api: Mesh API 0.6.1-alpha.21+1.16.4
		minecraft: Minecraft 1.16.5
		mostructures: Mo' Structures 1.0.1+mc.1.16.4
		net_dv8tion_jda: JDA 4.2.0_224
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_json_json: json 20170516
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		phosphor: Phosphor 0.7.0+build.10
		projectsavethepets: Project: Save the Pets! 1.0.2+minecraft-1.16.4
		roughlyenoughitems: Roughly Enough Items 5.9.2
		roughlyenoughitems-api: REI (API) 5.9.2
		roughlyenoughitems-default-plugin: REI (Default Plugin) 5.9.2
		roughlyenoughitems-runtime: REI (Runtime) 5.9.2
		roughlyenoughresources: Roughly Enough Resources 2.1.3
		worldedit: WorldEdit 7.2.2+fc3c499
		yungsapi: YUNG's API 1.16.4-Fabric-1
	Player Count: 0 / 20; []
	Data Packs: vanilla (incompatible), file/armor statues v2.8.1.zip, file/armored elytra v1.0.3.zip, file/more mob heads v2.8.2.zip, file/fast leaf decay v2.0.3.zip, file/multiplayer sleep v2.5.2.zip, file/graves v2.8.0.zip, file/spawn v2.3.0.zip, file/cauldron concrete v2.0.3.zip, file/homes v1.4.1.zip, file/larger phantoms v1.2.1.zip, file/player head drops v1.1.0.zip, file/unlock all recipes v2.0.0.zip, Fabric Mods, file/VanillaTweaks_c748942.zip, file/custom nether portals v2.3.2.zip, file/villager workstation highlights v1.1.0.zip, file/wandering trades v1.4.0.zip, file/anti enderman grief v1.1.0.zip, file/back v1.2.0.zip, file/Repurposed_Structures-Disabled_Advancements.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

</details>

**Additional context**

- Minecraft version: 1.16.5
- Fabric-Discord Link version: 0.8.8
- :exclamation: A list of all mods you were using:
AnvilFix
Chunky Chunk Loader
Door(s) Couplings
Fabric-API
FabricTPA
Fast Furnace
Lengthy Ladders
Lithium
Mo' Structures
Phosphur
Project: Save the Pets
Roughly Enough Resources
Roughly Enough Items
Sodium
Worldedit
YUNG's API, Caves, Mineshafts

**fdlink.json**
https://gist.github.com/Avakining/8b55735c97200f9dba3776871beead23

**Comment by thecatcore** [comment]
Can you also send your message config?

**Comment by Avakining** [comment]
[messages.json](https://gist.github.com/Avakining/e9aa525c0360303196feab3e4249d370)

(It's the default for the config)

**Comment by thecatcore** [comment]
Does it crashes only when Fabric Discord Link is installed? Have you tried launching the server without it?

**Comment by DTRW919** [comment]
Same thing happens to me, I run server without it and it's fine. Just with it, I did the exact same things Avakining did D:

**Comment by Patate324** [comment]
The same happens to me but it did work until there was nobody on the server and then it died
Mods in common: Fabric-API, Lithium, Phosphor, Sodium
When i remove the Fabric-Discord-Link .jar it fixes it and no longer crashes
I should make the following clear:
1)added  Fabric-Discord-Link .jar
2) boot server
2) join server, no problems, can play fine
3) close server
4) add token and channels
5) boot server
6) join server,  (Works completely fine, works well, both channels work as they should)
7) leave server, game crashes
- wont boot up again after this

**Comment by thecatcore** [comment]
Unable to reproduce sadly :(
