### ISSUE TITLE
Makes the game crash

### ISSUE THREAD

**Issue by Patate324** [arthurbambou/Fabric---Discord-Link#149]
Installed and everything worked fine (honestly it worked great!), but then when the last person left the dedicated server, **the game crashed with the following description:** 
"Exception in server tick loop"

**At the same time (seconds after) it also created another crash-report with description:**
Watching Server
java.lang.Error: Watchdog
	at net.minecraft.class_3178.run(class_3178.java:52)
	at java.lang.Thread.run(Thread.java:748)

**Both said this:** 
net.dv8tion.jda.api.exceptions.MissingAccessException: Cannot perform action due to a lack of Permission. Missing permission: VIEW_CHANNEL
at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkAccess(AbstractChannelImpl.java:307)
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:316)
	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:313)
	at net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:353)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToLogChannels(DiscordBot.java:315)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToLogChannels(DiscordBot.java:294)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendMessage(DiscordBot.java:267)
	at fr.arthurbambou.fdlink.FDLink1_16.handleText(FDLink1_16.java:69)
	at net.minecraft.server.MinecraftServer.handler$zik000$sendMessage(MinecraftServer.java:3712)
	at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java)
	at net.minecraft.class_3324.method_14616(class_3324.java:810)
	at net.minecraft.class_3244.method_10839(class_3244.java:1114)
	at net.minecraft.class_2535.method_10768(class_2535.java:396)
	at net.minecraft.class_3242.method_14357(class_3242.java:186)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:882)
	at net.minecraft.class_3176.method_3813(class_3176.java:312)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:811)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:670)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257)
	at java.lang.Thread.run(Thread.java:748)

Now when I open the server back up, it loads and after loading advancements, it says the same problem with "Exception in server tick loop" and the server wont start...

Now the crash reports are telling me to "try our sister game, Minceraft!"
If you can help it would be appreciated :)

**Comment by Patate324** [comment]
UPDATE: I had hidden my log channel in the server and the bot could not access it. This made the game crash. It no longer crashes after I give the bot permissions: To avoid this, i probably could have given the bot administrator permissions, but i just gave it relevant permissions in the specific hidden discord channel

**Comment by thecatcore** [comment]
so the issue is resolved?
