### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by B13D4R** [arthurbambou/Fabric---Discord-Link#167]
[Server thread/ERROR]: This crash report has been saved to: /./crash-reports/crash-2021-08-12_16.08.24-server.txt
[12.08 16:08:24] [Server] [Server thread/ERROR]: Exception stopping the server
[12.08 16:08:24] [Server] net.dv8tion.jda.api.exceptions.InsufficientPermissionExceptionCannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE
[12.08 16:08:24] [Server] 	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:329) ~[8e0a0e97-99bf-4bd9-a54e-4c47d628d3c3.jar:?]
[12.08 16:08:24] [Server] 	at net.dv8tion.jda.internal.entities.AbstractChannelImpl.checkPermission(AbstractChannelImpl.java:320) ~[8e0a0e97-99bf-4bd9-a54e-4c47d628d3c3.jar:?]
[12.08 16:08:24] [Server] 	at net.dv8tion.jda.internal.entities.TextChannelImpl.sendMessage(TextChannelImpl.java:347) ~[8e0a0e97-99bf-4bd9-a54e-4c47d628d3c3.jar:?]
[12.08 16:08:24] [Server] 	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToChatChannels(DiscordBot.java:334) ~[a2c3b3ba-058c-4e3d-ad81-7ba26b76647d.jar:?]
[12.08 16:08:24] [Server] 	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToChatChannels(DiscordBot.java:298) ~[a2c3b3ba-058c-4e3d-ad81-7ba26b76647d.jar:?]
[12.08 16:08:24] [Server] 	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.serverStopping(DiscordBot.java:116) ~[a2c3b3ba-058c-4e3d-ad81-7ba26b76647d.jar:?]
[12.08 16:08:24] [Server] 	at fr.arthurbambou.fdlink.FDLink1_16.lambda$onInitializeServer$4(FDLink1_16.java:74) ~[7c49e7e3-3f73-4593-ac40-c37f122e2b87.jar:?]
[12.08 16:08:24] [Server] 	at net.fabricmc.fabric.api.event.lifecycle.v1.ServerLifecycleEvents.lambda$static$4(ServerLifecycleEvents.java:62) ~[e50dcb8a-3dd1-4d4c-9e34-886045a017b4.jar:?]
[12.08 16:08:24] [Server] 	at net.minecraft.server.MinecraftServer.handler$zjd000$beforeShutdownServer(MinecraftServer.java:4312) ~[intermediary-server.jar:?]
[12.08 16:08:24] [Server] 	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java) ~[intermediary-server.jar:?]
[12.08 16:08:24] [Server] 	at net.minecraft.class_3176.method_3782(class_3176.java:585) ~[intermediary-server.jar:?]
[12.08 16:08:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:734) ~[intermediary-server.jar:?]
[12.08 16:08:24] [Server] 	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270) ~[intermediary-server.jar:?]
[12.08 16:08:24] [Server] 	at java.lang.Thread.run(Thread.java:831) [?:?]

**Comment by thecatcore** [comment]
`net.dv8tion.jda.api.exceptions.InsufficientPermissionExceptionCannot perform action due to a lack of Permission. Missing permission: MESSAGE_WRITE`
