### ISSUE TITLE
Server crashes due to mod

### ISSUE THREAD

**Issue by ghost** [arthurbambou/Fabric---Discord-Link#170]
**Describe the bug**

**Reproduction steps**

1. Do this Install the mod
2. run the server
3. run it without issues for 2 weeks
4. after roughly 2 weeks the server should constantly crash and frezze for no reason 

**Expected behavior**

<server crashes sooner and sooner first time 12h then 6h then 3h then 1h then 30min ect> 
  <watchdog says doing a long operation on the Main Thread, and Watchdog kills the server><strong>Crash report</	---- ></?>
 

```
	---- Minecraft Crash Report ----
// I feel sad now :(

Time: 10/31/21, 3:46 PM
Description: Exception in server tick loop

java.lang.IllegalStateException: Was shutdown trying to await status
	at net.dv8tion.jda.internal.JDAImpl.awaitStatus(JDAImpl.java:479)
	at net.dv8tion.jda.api.JDA.awaitStatus(JDA.java:316)
	at net.dv8tion.jda.api.JDA.awaitReady(JDA.java:366)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToChatChannels(DiscordBot.java:331)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendToChatChannels(DiscordBot.java:298)
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendMessage(DiscordBot.java:264)
	at fr.arthurbambou.fdlink.FDLink1_16.handleText(FDLink1_16.java:69)
	at net.minecraft.server.MinecraftServer.handler$bdk000$sendMessage(MinecraftServer.java:6278)
	at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java)
	at net.minecraft.class_3324.method_14616(class_3324.java:766)
	at net.minecraft.class_3244.method_10839(class_3244.java:1133)
	at net.minecraft.class_2535.method_10768(class_2535.java:415)
	at net.minecraft.class_3242.method_14357(class_3242.java:196)
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:902)
	at net.minecraft.class_3176.method_3813(class_3176.java:335)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:831)
	at net.minecraft.server.MinecraftServer.handler$zmd000$modifiedRunLoop(MinecraftServer.java:4890)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:676)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:270)
	at java.base/java.lang.Thread.run(Thread.java:831)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.17.1
	Minecraft Version ID: 1.17.1
	Operating System: Linux (amd64) version 5.4.0-81-generic
	Java Version: 16.0.2, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 3205174784 bytes (3056 MiB) / 6685720576 bytes (6376 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 4
	Processor Vendor: GenuineIntel
	Processor Name: Intel(R) Xeon(R) E-2288G CPU @ 3.70GHz
	Identifier: Intel64 Family 6 Model 158 Stepping 13
	Microarchitecture: Coffee Lake
	Frequency (GHz): 3.70
	Number of physical packages: 6
	Number of physical CPUs: 6
	Number of logical CPUs: 6
	Graphics card #0 name: unknown
	Graphics card #0 vendor: unknown
	Graphics card #0 VRAM (MB): 0.00
	Graphics card #0 deviceId: unknown
	Graphics card #0 versionInfo: unknown
	Virtual memory max (MB): 23679.60
	Virtual memory used (MB): 27411.90
	Swap memory total (MB): 7999.00
	Swap memory used (MB): 6997.52
	JVM Flags: 2 total; -Xms128M -Xmx8192M
	Fabric Mods: 
		carpet: Carpet Mod 1.4.50
		club_minnced_discord-webhooks: discord-webhooks 0.5.8
		com_fasterxml_jackson_core_jackson-annotations: jackson-annotations 2.10.1
		com_fasterxml_jackson_core_jackson-core: jackson-core 2.10.1
		com_fasterxml_jackson_core_jackson-databind: jackson-databind 2.10.1
		com_neovisionaries_nv-websocket-client: nv-websocket-client 2.14
		com_squareup_okhttp3_okhttp: okhttp 3.14.9
		com_squareup_okio_okio: okio 1.17.2
		com_vdurmont_emoji-java: emoji-java 5.1.1
		com_velocitypowered_velocity-native: velocity-native 1.1.0-SNAPSHOT
		dynmap: Dynmap 3.2-beta-3
		fabric: Fabric API 0.40.1+1.17
		fabric-api-base: Fabric API Base 0.3.0+a02b446318
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.0+cbda931818
		fabric-biome-api-v1: Fabric Biome API (v1) 3.2.0+cbda931818
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+5ab9934c18
		fabric-commands-v0: Fabric Commands (v0) 0.2.2+92519afa18
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+cbda931818
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.3.0+cbda931818
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.5+be9da31018
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.11+6cefd57718
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.3+87cc6e4c18
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.10+fc40aa9d18
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.1+92519afa18
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+cbda931818
		fabric-item-api-v1: Fabric Item API (v1) 1.2.4+cbda931818
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.2.10+b7ab612118
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.4.4+a02b446318
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.4+a02b446318
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.3+92519afa18
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.13+cbda931818
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.11+a02b446318
		fabric-networking-v0: Fabric Networking (v0) 0.3.2+92519afa18
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.10.9+cbda931818
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+a02b446318
		fabric-particles-v1: Fabric Particles (v1) 0.2.4+a02b446318
		fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.10+e2961fee18
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.5+a02b446318
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.14+4658223018
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+a00e834b18
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.8+cbda931818
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.13+5ab9934c18
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.2.1+b06cb95b18
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.12+b7ab612118
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.3.1+4658223018
		fabricloader: Fabric Loader 0.11.7
		fdlink: Fabric <-> Discord Link 0.9.8
		fdlink_1_12_2: Fabric <-> Discord Link 0.9.8
		fdlink_1_15_2: Fabric <-> Discord Link 0.9.8
		fdlink_1_16: Fabric <-> Discord Link 0.9.8
		fdlink_1_7_10: Fabric <-> Discord Link 0.9.8
		fdlink_1_8_9: Fabric <-> Discord Link 0.9.8
		fdlink_api: Fabric <-> Discord Link API 0.1.1
		fdlink_common: Fabric <-> Discord Link 0.9.8
		ferritecore: FerriteCore 3.0.3
		invview: InvView 1.4.6-1.17.1+
		java: OpenJDK 64-Bit Server VM 16
		krypton: Krypton 0.1.4
		lithium: Lithium 0.7.4
		minecraft: Minecraft 1.17.1
		net_dv8tion_jda: JDA 4.3.0_323
		net_sf_trove4j_trove4j: trove4j 3.0.3
		org_apache_commons_commons-collections4: commons-collections4 4.1
		org_json_json: json 20210307
		org_slf4j_slf4j-api: slf4j-api 1.7.25
		org_slf4j_slf4j-nop: slf4j-nop 1.7.25
		perplayerspawns: Example Mod 1.17-2.0.0
		sgui: SGui 1.0.0-rc4+1.17.1
		starlight: Starlight 1.0.0+fabric.73f6d37
	Player Count: 4 / 20; [class_3222['daddy_ashlyn'/75, l='ServerLevel[world]', x=3205.81, y=63.80, z=-957.83], class_3222['Morsznetik'/527, l='ServerLevel[world]', x=1018.45, y=67.00, z=-1241.70], class_3222['I_Lord_your_god'/5177, l='ServerLevel[world]', x=5287.06, y=79.00, z=9188.68], class_3222['JoelVongNameHer'/42122, l='ServerLevel[world]', x=2987.39, y=71.00, z=-1083.29]]
	Data Packs: vanilla, file/coordinates hud v1.2.0.zip, file/afk display v1.1.0.zip, file/armor statues v2.8.1.zip, file/cauldron concrete v2.0.3.zip, file/count mob deaths v1.1.0.zip, file/custom nether portals v2.3.2.zip, file/more mob heads v2.9.2.zip, file/multiplayer sleep v2.6.1.zip, file/nether portal coords v1.1.0.zip, file/player head drops v1.1.0.zip, file/redstone rotation wrench v1.1.1.zip, file/silence mobs v1.1.0.zip, file/terracotta rotation wrench v1.1.1.zip, file/track raw statistics v1.5.0.zip, file/villager death messages v1.2.1.zip, Fabric Mods, file/dragon drops v1.3.0.zip
	Is Modded: Definitely; Server brand changed to 'fabric'
	Type: Dedicated Server (map_server.txt)
```

</details>

**Additional context**
The server and bot runs like intended but after a few weeks without any issues the server starts crashing and complaining about the mod

- Minecraft version:1.17.1
- Fabric-Discord Link version:0.9.8
- :exclamation: A list of all mods you were using: 
Dynmap-3.2-beta-3-fabric-1.17.1_1.jar
EntityCulling-Fabric-1.3.3.jar
fabric-api-0.40.11.17 (1).jar
fabric-carpet-1.17.1-1.4.50+v211021.jar
fabric-per-player-spawns-1.17-2.0.0.jar
ferritecore-3.0.3-fabric.jar
InvView-1.4.6-1.17.1+.jar
krypton-0.1.4.jar
lithium-fabric-mc1.17.1-0.7.4 (1).jar
starlight-1.0.0+fabric.73f6d37.jar
**fdlink.json**
Please attach your configuration file (`fdlink.json`) here (edit the token out)
	{
  "token": "",
  "chatChannels": [
    "895685840196485160"
  ],
  "logChannels": [
    "895685840196485160"
  ],
  "webhook": {
    "url": "",
    "mentions": {
      "everyone": false,
      "roles": false,
      "users": true
    }
  },
  "ignoreBots": true,
  "activityUpdateInterval": 120,
  "minecraftToDiscord": {
    "general": {
      "enableDebugLogs": false
    },
    "chatChannels": {
      "commandPrefix": "-",
      "allowDiscordCommands": false,
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": true,
      "teamPlayerMessages": true,
      "joinAndLeaveMessages": true,
      "advancementMessages": true,
      "challengeMessages": true,
      "goalMessages": true,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": false,
      "atATellRaw": false,
      "achievementMessages": true
    },
    "logChannels": {
      "serverStartingMessage": true,
      "serverStartMessage": true,
      "serverStopMessage": true,
      "serverStoppingMessage": true,
      "customChannelDescription": false,
      "minecraftToDiscordTag": false,
      "minecraftToDiscordDiscriminator": false,
      "playerMessages": false,
      "teamPlayerMessages": false,
      "joinAndLeaveMessages": true,
      "advancementMessages": false,
      "challengeMessages": false,
      "goalMessages": false,
      "deathMessages": true,
      "sendMeCommand": true,
      "sendSayCommand": true,
      "adminMessages": true,
      "atATellRaw": false,
      "achievementMessages": true
    }
  },
  "discordToMinecraft": {
    "pingLongVersion": false
  },
  "emojiMap": [
    {
      "name": "example_name",
      "id": ":example_id:22222222"
    },
    {
      "name": "example_name2",
      "id": ":example_id2:22222222"
    }
  ],
  "version": 9
}

**Comment by GlitchApotamus** [comment]
Ensure your bot token is correct (regenerate the token if needed). Then move on to your server. Make sure your bot has the proper permissions per channel. Temporarily add the Admin perm to see if it helps.
