### ISSUE TITLE
Mod prevents shutdown of server on 1.16.1

### ISSUE THREAD

**Issue by LevelZero-dev** [arthurbambou/Fabric---Discord-Link#75]
When I use Fabric-Discord Link on a 1.16.1 server, everything works nicely until I stop the server .. somehow the Fabric launcher process never stops .. by process of elimination (adding/removing mods), I pinpointed the issue to this specific mod. The bot nicely posts "Server stopped" into Discord and goes offline, but the launcher doesn't terminate.

Using Fabric 0.8.8-build 202, Fabric-API 0.13-build 370 and Fabric-Discord Link 0.3.6 downloaded from curseforge. OS is CentOS 8.1, Java is OpenJDK 1.8

**Comment by meadowsys** [comment]
got the same exact issue.
here are details: loader v0.6.1.45, fabric-api-0.14.0+build.371-1.16 and FDLink-0.4.1

java details:
on linux mint 19.3:
```
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode)
```
on windows 10 1903:
```
java version "14" 2020-03-17
Java(TM) SE Runtime Environment (build 14+36-1461)
Java HotSpot(TM) 64-Bit Server VM (build 14+36-1461, mixed mode, sharing)
```
here is the server shutdown logs:
```
[16:48:51] [Server thread/INFO]: Stopping the server
[16:48:51] [Server thread/ERROR]: [FDLink] Unhandled text "commands.stop.stopping":Stopping the server
[16:48:51] [Server thread/INFO]: Stopping server
[16:48:51] [Server thread/INFO]: Saving players
[16:48:51] [Server thread/INFO]: Saving worlds
[16:48:51] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:overworld
[16:48:52] [ReadingThread/INFO]: Websocket closed with reason 'unknown' and code NORMAL (1000) by client!
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:48:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_nether
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:48:54] [Server thread/INFO]: Saving chunks for level 'ServerLevel[world]'/minecraft:the_end
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (world): All chunks are saved
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[16:48:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
// hung here for a really long time (>10m)
^C
```
I found it is safe to `ctrl+c` to end the server process. I suspect there is some thread that hasn't shutdown properly.

**Comment by PssbleTrngle** [comment]
Same, I was wondering what caused it

**Comment by DDR-Khat** [comment]
I would like to also echo that this does also happen. I cannot see from the logs any reason that would suggest it's hung there than perhaps there is a very slow gradual memory leak or something that takes longer to purge when the server shuts down?

**Comment by PssbleTrngle** [comment]
I think the mod tries to handle the server shutdown message but cant and probably throws a `ClassCastException`, preventing the server from further shutting down.
The server freezes because the error occures while it is already trying to shut down

**Comment by josephrooks** [comment]
This happened to me in 1.14 and 1.15 as well, although if I let it sit long enough, it would actually shut down.

**Comment by ghost** [comment]
Setting booleans.serverStopMessage to false seems to not hang the server on shutdown.

**Comment by thecatcore** [comment]
I tested it in dev and the fix I found works perfectly.

**Comment by PegasusEpsilon** [comment]
@arthurbambou Kato and I have been digging through the code trying to work it out, what is your fix?

**Comment by thecatcore** [comment]
the issue was that when the "server stopped" message was sent, It wasn't waiting on the message received event to be fully done before disconnecting the bot

**Comment by thecatcore** [comment]
the code fixing it : 
https://github.com/arthurbambou/Fabric---Discord-Link/blob/1.16/src/main/java/fr/arthurbambou/fdlink/discordstuff/DiscordBot.java#L77-L81
https://github.com/arthurbambou/Fabric---Discord-Link/blob/1.16/src/main/java/fr/arthurbambou/fdlink/discordstuff/DiscordBot.java#L112-L117

**Comment by PegasusEpsilon** [comment]
Correct me if I'm wrong, but wouldn't having more than one channel configured result in the bot API shutting down on the first echo, and therefore still prematurely?

**Comment by thecatcore** [comment]
It was happening also when only one channel was in the config.

**Comment by PegasusEpsilon** [comment]
Right, but I'm saying, with your patch, I think it will still happen when more than one channel is in the config.

**Comment by thecatcore** [comment]
you are right :thinking: .

**Comment by thecatcore** [comment]
I've just tested it with a log channel.

**Comment by PegasusEpsilon** [comment]
As I said in my patch, I barely know java, so we're still toying with ideas, but Kato was suggesting promise resolution might be the java way, but outside of java I'd use an atomic to count event handler lambdas when the event is queued, and again when it's fired and thus dequeued, then when there are none pending, tear down the API.

EDIT: This also has the benefit of not waiting for the echo, which may never come if discord hiccups, resulting in a stall anyway.

**Comment by ghost** [comment]
In javascript the asynchronous sending of messages would return a promise.  You can then await the resolution of these promises before continuing with the rest of the code.  I don't know if java has similar concepts.

**Comment by thecatcore** [comment]
I know, but in this case, the problem seems to be that the message is being received back just after being sent.

**Comment by PegasusEpsilon** [comment]
Hm, we were thinking it would be a problem of trying to fire the channel.sendMessage lambda after the API is already disconnected. If pending messages on disconnect are the problem, you're going to have to clear the pending message event handler before even disconnecting, right?

EDIT: I suppose you could use the echo method to count fulfilled promises, but that still relies on the discord server not having a seizure in the middle of server shutdown, which can't be guaranteed.

**Comment by thecatcore** [comment]
I found a solution ^^. I'm working on it right now.

**Comment by thecatcore** [comment]
New version with the working fix : https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/3008222

**Comment by meadowsys** [comment]
cool, thank you!

**Comment by DDR-Khat** [comment]
`[15:23:54] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[15:23:54] [Server thread/ERROR]: Exception stopping the server
java.lang.NullPointerException: null
	at fr.arthurbambou.fdlink.discordstuff.DiscordBot.lambda$new$5(DiscordBot.java:109) ~[FDLink-0.4.4.jar:?]
	at net.minecraft.server.MinecraftServer.handler$zzo000$afterShutdownServer(MinecraftServer.java:1739) ~[intermediary-server-1-16-1.jar:?]
	at net.minecraft.server.MinecraftServer.method_3782(MinecraftServer.java:620) ~[intermediary-server-1-16-1.jar:?]
	at net.minecraft.class_3176.method_3782(class_3176.java:556) ~[intermediary-server-1-16-1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:709) ~[intermediary-server-1-16-1.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server-1-16-1.jar:?]
	at java.lang.Thread.run(Thread.java:835) [?:?]
`

**Comment by PegasusEpsilon** [comment]
https://github.com/arthurbambou/Fabric---Discord-Link/blob/1.16/src/main/java/fr/arthurbambou/fdlink/discordstuff/DiscordBot.java#L109

Nasty lambda rears its head again. Null check before deref? try/catch? Work out and solve the underlying problem? The last one seems like the obvious right answer, but it's not exactly straightforward...
