### ISSUE TITLE
Entering wrong command stops server

### ISSUE THREAD

**Issue by PssbleTrngle** [arthurbambou/Fabric---Discord-Link#77]
It seems like the mod cannot handle the message the server sends when you enter an incorrect command in the terminal.

```
[22:10:57] [Server thread/INFO]: Unknown or incomplete command, see below for error
[22:10:57] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.ClassCastException: net.minecraft.class_2585 cannot be cast to net.minecraft.class_2588
        at fr.arthurbambou.fdlink.discordstuff.todiscord.MinecraftToDiscordHandler.handleTexts(MinecraftToDiscordHandler.java:188) ~[FDLink-0.4.1.jar:?]
        at fr.arthurbambou.fdlink.discordstuff.DiscordBot.sendMessage(DiscordBot.java:165) ~[FDLink-0.4.1.jar:?]
        at net.minecraft.server.MinecraftServer.handler$zfp000$sendMessage(MinecraftServer.java:3198) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_9203(MinecraftServer.java:987) ~[intermediary-server.jar:?]
        at net.minecraft.class_2168.method_9213(class_2168.java:237) ~[intermediary-server.jar:?]
        at net.minecraft.class_2170.method_9249(class_2170.java:265) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_13941(class_3176.java:334) ~[intermediary-server.jar:?]
        at net.minecraft.class_3176.method_3813(class_3176.java:307) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:813) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:672) ~[intermediary-server.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:256) ~[intermediary-server.jar:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by trunkyredstone** [comment]
I'm also having this.

**Comment by arthurbambou** [comment]
I will fix it Wednesday afternoon (UTC+2)

**Comment by thecatcore** [comment]
https://www.curseforge.com/minecraft/mc-mods/fabric-discord-link/files/2994231
