### ISSUE TITLE
Server crashing on startup

### ISSUE THREAD

**Issue by zischknall** [arthurbambou/Fabric---Discord-Link#91]
I am trying to run a server with following mods:
 - lithium
 - phosphor
 - fabric-api
 - spark
 - discord-link

I have filled in the config file but I am getting this error on startup:
```
[14:47:35] [main/INFO]: Loading for game Minecraft 1.16.1
[14:47:36] [main/INFO]: [FabricLoader] Loading 58 mods: fabric-renderer-api-v1@0.2.13+eae12eb802, fabric-keybindings-v0@0.2.0+3fa9f7c502, fabricloader@0.9.0+build.204, com_fasterxml_jackson_core_jackson-annotations@2.9.0, org_javacord_javacord-api@3.0.6, org_javacord_javacord-core@3.0.6, lithium@0.5.1, fabric-containers-v0@0.1.8+045df74f02, fabric-object-builder-api-v1@1.5.6+a2d21ddd02, fabric-dimensions-v1@1.0.0+a71b305302, com_squareup_okio_okio@1.13.0, minesave@1.16-1.3.0, fabric-api-base@0.1.3+12a8474c02, fabric-rendering-data-attachment-v1@0.1.3+b7f9825d02, fabric-textures-v0@1.0.4+eae12eb802, fabric-rendering-fluids-v1@0.1.8+b7084faa02, com_fasterxml_jackson_core_jackson-databind@2.9.3, com_neovisionaries_nv-websocket-client@2.6, fabric-blockrenderlayer-v1@1.1.4+c6a8ea8902, fabric-lifecycle-events-v1@1.1.0+013e49d202, fabric-renderer-registries-v1@2.0.1+5a0f9a6002, fabric-loot-tables-v1@1.0.0+386eb69e02, com_vdurmont_emoji-java@5.1.1, com_fasterxml_jackson_core_jackson-core@2.9.3, fabric@0.15.1+build.380-1.16.1, fabric-particles-v1@0.2.1+0a6f2a7002, fabric-networking-v0@0.1.10+e00ecb5f02, org_apache_httpcomponents_httpmime@4.5.12, minecraft@1.16.1, fabric-screen-handler-api-v1@1.1.0+97324d1102, fabric-networking-blockentity-v0@0.2.5+b50ffc7b02, fabric-command-api-v1@1.0.8+5ce5339802, com_squareup_okhttp3_logging-interceptor@3.9.1, phosphor@0.6.0+build.7, fabric-tool-attribute-api-v1@1.1.4+5794386e02, fabric-renderer-indigo@0.3.3+0a55f37902, fabric-biomes-v1@0.2.7+059ea86602, fabric-item-api-v1@1.0.0+16acbe5b02, fabric-events-interaction-v0@0.3.3+7066030f02, fabric-crash-report-info-v1@0.1.2+b7f9825d02, spark@1.4.3, fabric-rendering-v0@1.1.0+5341049002, fabric-rendering-v1@1.1.2+346247d702, fabric-key-binding-api-v1@1.0.1+f404f3be02, fabric-resource-loader-v0@0.2.6+f41e209802, fabric-content-registries-v0@0.1.9+059ea86602, org_json_json@20170516, fabric-tag-extensions-v0@0.2.7+a4c57d8e02, fabric-registry-sync-v0@0.3.8+7dba2d6c02, fabric-commands-v0@0.2.0+52d3083602, com_squareup_okhttp3_okhttp@3.9.1, fabric-mining-levels-v0@0.1.2+b764ce9902, org_apache_logging_log4j_log4j-api@2.11.0, fabric-events-lifecycle-v0@0.2.0+16acbe5b02, fabric-models-v0@0.1.0+dfdb52d602, fabric-item-groups-v0@0.2.0+438f963602, fabric-object-builders-v0@0.6.1+a2d21ddd02, fdlink@0.4.4
[14:47:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/opt/minecraft/vanilla/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[14:47:38] [main/WARN]: @Mixin target net/minecraft/class_3898$class_3208 is public in fabric-networking-[14:47:41] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', name='PROD'
[14:47:43] [WritingThread/INFO]: Websocket closed with reason 'Authentication failed.' and code AUTHENTICATION_FAILED (4004) by server!
[14:47:43] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'fdlink'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:125) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:192) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.init(Knot.java:140) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:26) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:61) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:105) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:49) [fabric-server-launch.jar:?]
Caused by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Websocket closed before READY packet was received!
        at java.util.concurrent.CompletableFuture.reportJoin(CompletableFuture.java:412) ~[?:?]
        at java.util.concurrent.CompletableFuture.join(CompletableFuture.java:2044) ~[?:?]
        at fr.arthurbambou.fdlink.discordstuff.DiscordBot.<init>(DiscordBot.java:77) ~[FDLink-0.4.4.jar:?]
        at fr.arthurbambou.fdlink.FDLink.onInitializeServer(FDLink.java:27) ~[FDLink-0.4.4.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: java.lang.IllegalStateException: Websocket closed before READY packet was received!
        at org.javacord.core.DiscordApiImpl.lambda$new$6(DiscordApiImpl.java:529) ~[4c5368af-965c-4599-a72f-af8893ffdbf9.jar:?]
        at java.util.concurrent.CompletableFuture.uniWhenComplete(CompletableFuture.java:859) ~[?:?]
        at java.util.concurrent.CompletableFuture$UniWhenComplete.tryFire(CompletableFuture.java:837) ~[?:?]
        at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:506) ~[?:?]
        at java.util.concurrent.CompletableFuture.complete(CompletableFuture.java:2073) ~[?:?]
        at org.javacord.core.util.gateway.DiscordWebSocketAdapter.onDisconnected(DiscordWebSocketAdapter.java:464) ~[4c5368af-965c-4599-a72f-af8893ffdbf9.jar:?]
        at com.neovisionaries.ws.client.ListenerManager.callOnDisconnected(ListenerManager.java:223) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WebSocket.finish(WebSocket.java:3713) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WebSocket.onThreadsFinished(WebSocket.java:3683) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WebSocket.onWritingThreadFinished(WebSocket.java:3672) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WritingThread.notifyFinished(WritingThread.java:539) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WritingThread.runMain(WritingThread.java:78) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
        at com.neovisionaries.ws.client.WebSocketThread.run(WebSocketThread.java:45) ~[f5967c76-560a-4e02-9804-dd41005bdfe2.jar:?]
```

I think its caused by the constructor of DiscordBot here: 
```
this.api = new DiscordApiBuilder().setToken(token).login().join();
        MessageCreateListener messageCreateListener = (event -> {
            if (event.getMessageAuthor().isBotUser() && this.config.ignoreBots) return;
            if (!this.hasChatChannels) return;
            if (event.getMessageAuthor().isYourself()) return;
            if (!this.config.chatChannels.contains(event.getChannel().getIdAsString())) return;
            this.messageCreateEvent = event;
            this.hasReceivedMessage = true;
        });
```

**Comment by LevelZero-dev** [comment]
You say you have "filled" the config, but the "Authentication Failed" message for me points to a missing or incorrect token.
Did you follow the instructions for creating a new Discord application and getting the token from https://github.com/arthurbambou/Fabric---Discord-Link/wiki/How-to-get-a-token-and-channel-ID-for-Discord or did you just copy the token from the example?

**Comment by zischknall** [comment]
No I copied the actual token from the Discord Developer Portal where it says client Secret. I also had this working already before with the Spigot Plugin called DiscordSRV so I know how it works. I even regenerated the token and pasted it in, but same problem.
If you need any more information, ping me.

**Comment by LevelZero-dev** [comment]
The Client Secret is the wrong thing. You need the token from the Bot page.

**Comment by zischknall** [comment]
@LevelZero-dev Which is called Client Secret the other thing on there is Client ID

**Comment by zischknall** [comment]
Sorry I got it wrong i misremembered the stuff and only flew over it because I had done it before. I was only looking at the App not the Bot.
